### ISSUE TITLE
project URL available for other users

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#14]
Need to decide/design API when user generates URL of project and send it to somebody else.
Somebody else currently can't view the project - as URL doesn't return the project and datasets available. Frontend currently shows the projects owned by user - not by others.

Proposal:
Option 1)
- Frontend will recognize that the URL doesn't link to any of his projects, so subsequent call to backend REST API is made with projectID to get details - it is returned even the user doesn't have permission on it

Option 2)
- we need to add some attribute that the project is e.g. available for anybody with link
- Frontend will recognize that the URL doesn't link to any of his projects, so subsequent call to backend REST API is made with projectID to get details - it is returned only if previous is true for the project (set by owner)
- we may log who access this project/datasets

**Comment by andreagia** [comment]
Proposal:

we need to add some attribute that the project is e.g. available for anybody with link
Frontend will recognize that the URL doesn't link to any of his projects, so subsequent call to backend REST API is made with projectID to get details - it is returned only if 1) is true (set by user)
we may log who access this project/datasets

I can simply add an attribute ‘shareable' to the project and an hash of 5 character like bitly and a service like  /sharedProject/Eddf5 to access it,
for the login we can use social network login in order to take trace of the access 

Andrea

**Comment by TomasKulhanek** [comment]
Do you have some support for authorizing requests in Spring framework? Can you do that on /project/[id]? and /dataset/[id]

After that frontend need to define authorization for projects and datasets to allow access to 1) all 2) selected users/groups 3) nobody

**Comment by andreagia** [comment]
Using spring ACL I will try to secure these methods

**Comment by TomasKulhanek** [comment]
And how the authorization can be managed by frontend? I’d like to do it from Aurelia using some REST call. Or does there already exists some easy JSP pages?
T.

**Comment by TomasKulhanek** [comment]
- [ ] These methods are not ready yet on backend. 
- [ ] need instruction on how the authorization can be managed by frontend.
